# Generated by Django 5.1.1 on 2024-10-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_plantio', models.DateField()),
                ('data_colheita', models.DateField()),
                ('duracao', models.IntegerField()),
                ('unidade_duracao', models.CharField(max_length=10)),
                ('irrigacao_frequencia', models.IntegerField()),
                ('irrigacao_unidade', models.CharField(max_length=10)),
                ('poda_frequencia', models.IntegerField()),
                ('poda_unidade', models.CharField(max_length=10)),
            ],
        ),
    ]
