# Generated by Django 5.1.1 on 2024-10-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0002_cultura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultura',
            old_name='localizacao',
            new_name='area',
        ),
        migrations.AddField(
            model_name='cultura',
            name='linha',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
