# Generated by Django 5.1.1 on 2024-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0003_rename_localizacao_cultura_area_cultura_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='atividades_adicionadas_frequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cultura',
            name='atividades_adicionadas_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cultura',
            name='atividades_adicionadas_unidade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
