# Generated by Django 5.1.1 on 2024-10-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0005_alter_cultura_atividades_adicionadas_frequencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='atividades_adicionadas_frequencia',
        ),
        migrations.RemoveField(
            model_name='cultura',
            name='atividades_adicionadas_nome',
        ),
        migrations.RemoveField(
            model_name='cultura',
            name='atividades_adicionadas_unidade',
        ),
    ]
