# Generated by Django 5.1.1 on 2024-10-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0006_remove_cultura_atividades_adicionadas_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
