# Generated by Django 5.1.1 on 2024-11-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0007_alter_cultura_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultura',
            name='irrigacao_frequencia',
        ),
        migrations.RemoveField(
            model_name='cultura',
            name='irrigacao_unidade',
        ),
        migrations.RemoveField(
            model_name='cultura',
            name='poda_frequencia',
        ),
        migrations.RemoveField(
            model_name='cultura',
            name='poda_unidade',
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('frequencia', models.IntegerField()),
                ('unidade_frequencia', models.CharField(choices=[('dias', 'dias'), ('semanas', 'semanas'), ('meses', 'meses'), ('anos', 'anos')], max_length=10)),
                ('data_proxima', models.DateField()),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_soli.cultura')),
            ],
        ),
    ]
