# Generated by Django 5.1.1 on 2024-11-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soli', '0008_remove_cultura_irrigacao_frequencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nota', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='diario_fotos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
