# Generated by Django 5.1.1 on 2024-10-28 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segunda_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='time_start',
        ),
        migrations.AddField(
            model_name='commitment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='description',
            field=models.TextField(default='Descrição padrão'),
        ),
    ]
